// Common disposable/temporary email domains, rejected at signup.
export const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
  'mailinator.com', 'guerrillamail.com', 'throwam.com', 'sharklasers.com',
  'guerrillamailblock.com', 'grr.la', 'guerrillamail.info', 'guerrillamail.biz',
  'guerrillamail.de', 'guerrillamail.net', 'guerrillamail.org', 'spam4.me',
  'trashmail.com', 'trashmail.at', 'trashmail.io', 'trashmail.me',
  'trashmail.net', 'yopmail.com', 'yopmail.fr', 'cool.fr.nf', 'jetable.fr.nf',
  'nospam.ze.tc', 'nomail.xl.cx', 'mega.zik.dj', 'speed.1s.fr',
  'courriel.fr.nf', 'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf',
  'dispostable.com', 'mailnull.com', 'spamgourmet.com', 'spamgourmet.net',
  'spamgourmet.org', 'spam.la', 'tempmail.com', 'temp-mail.org',
  'temp-mail.ru', 'discard.email', 'tempr.email', 'discardmail.com',
  'discardmail.de', 'throwam.com', 'maildrop.cc', 'fakeinbox.com',
  'getnada.com', 'anonaddy.com', 'inboxbear.com', 'spambox.us',
  'mailnesia.com', 'tempinbox.com', 'tempomail.fr', 'throwam.com',
  'emailondeck.com', 'getairmail.com', 'mailexpire.com', 'spamevader.com',
  'safetymail.info', 'dancemail.dk', 'spamfree24.org', 'dodgeit.com',
  'mailmoat.com', 'spamhole.com', 'pookmail.com', 'throwaway.email',
  'mailsac.com', 'binkmail.com', 'bobmail.info', 'chammy.info',
  'devnullmail.com', 'get1mail.com', 'jetable.com', 'trash-amil.com',
  'crazymailing.com', 'urgentmail.biz', 'dingbone.com', 'bodhi.lawlita.com',
  'meltmail.com', 'klzlk.com', 'spamstack.net', 'suremail.info',
  'spaml.de', 'coieo.com', 'tafmail.com', 'vipmail.pw',
  'deyom.com', 'thankyou2010.com', 'throwam.com', 'hulapla.de',
  'tmail.com', 'zippymail.info', 'mailforspam.com', 'spamgob.com',
  'spaml.com', 'trashdevil.com', 'trashdevil.de', 'mailblocks.com',
  'temporaryemail.net', 'emailisvalid.com', 'fakemailgenerator.com',
  'spamfree.eu', 'throwam.com', 'incognitomail.com', 'incognitomail.net',
  'incognitomail.org', 'mailexpire.com', 'safe-mail.net', 'spamgourmet.com',
  'dispostable.com', 'dontreg.com', 'dontsendmespam.de', 'dump-email.info',
  'e4ward.com', 'easytrashmail.com', 'einmalmail.de', 'email60.com',
  'emailinfive.com', 'emailisvalid.com', 'emailtemporario.com.br',
  'emailwarden.com', 'emz.net', 'enterto.com', 'ephemail.net',
  'explodemail.com', 'fakeinbox.org', 'fastacura.com', 'filzmail.com',
  'filzmail.de', 'fizmail.com', 'frapmail.com', 'fudgerub.com',
  'gelitik.in', 'gishpuppy.com', 'givmail.com', 'glitch.sx',
  'goodbye.email', 'gotmail.net', 'gotmail.org', 'gowikibooks.com',
  'gowikicampus.com', 'gowikicars.com', 'gowikifilms.com', 'gowikigames.com',
  'gowikimusic.com', 'gowikinetwork.com', 'gowikitravel.com', 'gowikitv.com',
  'grandmamail.com', 'grandmasmail.com', 'h8s.org', 'hakumail.com',
  'hatespam.org', 'herp.in', 'hidzz.com', 'hochsitze.com',
  'hosting.3utilities.com', 'hot-mail.gq', 'hotpop.com', 'hulapla.de',
  'temp-mail.io', 'tempmail.plus', 'tempmail.ninja',
  '1secmail.com', '1secmail.net', '1secmail.org', '1secmail.pl',
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '20minutemail.com',
  'mohmal.com', 'mohmal.im',
  'fakemail.com', 'fakemail.net', 'emailfake.com',
  'tmpmail.net', 'tmpmail.org',
  'tempemail.co', 'tempemail.net',
  'temporary-email.com', 'temporaryemail.com',
  'disposableemail.com', 'disposablemail.com',
  'trashmail.live', 'trashmail.xyz',
  'mailtemp.net', 'mailtemp.org', 'mailtemp.info',
  'spamhere.com', 'spamkill.info',
  'harakirimail.com', 'mintemail.com',
  'gettempemail.com', 'guerrillamail.co', 'guerrillamail.uk',
  'anonaddy.me',
  // Additional researched disposable/temporary domains from maintained public lists.
  '10min.email', '10minemail.com', '10minmail.de', '10minut.xyz',
  '10minutemail.be', '10minutemail.co.za', '10minutemail.nl',
  '10minutemail.pl', '10minutemail.us', '10minutenemail.de',
  '10minutenmail.xyz', '10minutesemail.net', '12minutemail.net',
  '20minutemail.it', '20minutesmail.com', '30minutenmail.eu',
  '60-minuten-mail.de', '60minutemail.com', 'my10minutemail.com',
  'zehnminuten.de', 'best-temp-mail.com', 'besttempmail.com',
  'boxtemp.com.br', 'courrieltemporaire.com', 'email-temp.com',
  'emailtemporanea.net', 'emailtemporar.ro', 'mail-temporaire.com',
  'mail-temporaire.fr', 'mailtemporaire.com', 'mailtemporaire.fr',
  'mytemp.email', 'mytempemail.com', 'temp-mail.de',
  'temp-mail.pp.ua', 'temp-mails.com', 'tempail.com',
  'tempe-mail.com', 'tempemail.biz', 'tempm.com', 'tempmail.de',
  'tempmail.dev', 'tempmail.it', 'tempmail.pp.ua', 'tempmail.us',
  'tempmailer.com', 'tempmailo.com', 'temporarioemail.com.br',
  'temporaryemail.us', 'tempthe.net', 'tempymail.com', 'faketemp.email',
  'cloud-temp.com', 'cybertemp.xyz', 'easy-trash-mail.com',
  'mail4trash.com', 'mailmetrash.com', 'mytrashmail.com',
  'mytrashmail.net', 'trash-mail.at', 'trash-mail.net', 'trash2009.com',
  'trash2010.com', 'trash2011.com', 'trash247.com', 'trashbox.eu',
  'trashcanmail.com', 'trashemail.de', 'trashinbox.net', 'trashmail.de',
  'trashmail.es', 'trashmail.fr', 'trashmail.hu', 'trashmail.se',
  'trashmail.top', 'trashmail.ws', 'trashmailer.com', 'trashmails.com',
  'trashymail.com', 'trashymail.net', 'fakeemail.de', 'fakeinbox.info',
  'fakemail.fr', 'fakemail.io', 'fakemail.top', 'fakemailz.com',
  'fakemyinbox.com', 'mail-fake.com', 'namefake.com', 'mail.tm',
  'mail.gw', 'mailcatch.com', 'mailpoof.com', 'mail7.io', 'fexbox.org',
  'fexpost.com', 'fextemp.com', 'inboxkitten.com', 'dropmail.me',
  'moakt.co', 'moakt.com', 'moakt.ws', 'tmail.ws', 'tmail6.com',
  'tmail9.com', 'tmails.net', 'tmailinator.com', 'throwaway.io',
  'throwawayemail.com', 'dispose.it', 'disposeamail.com',
  'privy-mail.com', 'privymail.de', 'anon-mail.de', 'you-spam.com',
  'sharkfaces.com', 'sharkmail.xyz', 'webmailshark.com',
  'damnthespam.com', 'deadspam.com', 'fightallspam.com', 'forspam.net',
  'haltospam.com', 'ieatspam.eu', 'ieatspam.info', 'iheartspam.org',
  'letthemeatspam.com', 'lilspam.com', 'magspam.net',
  'meinspamschutz.de', 'nogmailspam.info', 'nomorespamemails.com',
  'nonspam.eu', 'nonspammer.de', 'nospamthanks.info', 'nurfuerspam.de',
  'putthisinyourspamdatabase.com', 'sendspamhere.com', 'spamail.de',
  'spamavert.com', 'spambob.net', 'spambog.de', 'spambog.net',
  'spambog.ru', 'spambox.org', 'spamcero.com', 'spamcon.org',
  'spamcowboy.com', 'yopmail.net', 'yopmail.pp.ua', 'yopmail.info',
  'yopmail.org', 'yopmail.co', 'yopail.com', 'yopmai.com', 'yopp.com',
  'yoptruc.fr.nf',
]);
